### ISSUE TITLE
Add field for message content privileged intent.

### ISSUE THREAD

**Issue by jameswalston** [advaith1/libs#112]
As the message intent deadline is approaching, it may be valuable to bot developers wanting to find out which libraries currently support it. This could be anything from the bitshift flag being added to an Intents object used for authentication, or checking the application flags for authorization.

**Comment by advaith1** [comment]
Libraries don't need to add support for it; enabling the switch in the dev portal will make the bot receive message content on gateway v9 and below.

**Comment by jameswalston** [comment]
Resurfacing, but apparently v9 now requires the message content intent when it **very much** shouldn't. Would you be willing to reconsider?
